# Netlify Build Configuration
[build]
  # Directory to run build commands
  base = "."
  
  # Build command
  command = "npm run build"
  
  # Directory to deploy (build output)
  publish = "dist"

# Custom domain configuration
[[redirects]]
  from = "https://medali-mas.abuamar.site/*"
  to = "https://www.medali-mas.abuamar.site/:splat"
  status = 301
  force = true

# SPA routing - redirect all routes to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Performance headers for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Font optimization
[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
# Preload hints for better performance
[[headers]]
  for = "/"
  [headers.values]
    Link = "</assets/index.css>; rel=preload; as=style"
